### ISSUE TITLE
Private Only Tasks

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#20]
https://github.com/ubiquity/devpool-directory-private is our new "backend" to read private issues and populate them on the [devpool.directory](https://devpool.directory)

This should ONLY populate with private repository issues. This is so we don't have redundant data on the public and private directories.

Also re-enable "referencing" back to private repository issues (I just disabled it entirely in that repo as a quick fix by disabling the logic if its not the public devpool-directory repo https://github.com/ubiquity/devpool-directory-private/blob/development/helpers/github.ts#L63.) This means that the bot should paste in the normal URL in the GitHub comment so that the mirrored issue is "referenced" in the real issue conversation.

Ensure that this works as expected by testing the UI on the [devpool.directory](https://devpool.directory) (you must auth as a core team member)

**Comment by rndquu** [comment]
Perhaps we need some github env variable like `READ_ISSUES_MODE=public|private` which should be `public` for https://github.com/ubiquity/devpool-directory and `private` for https://github.com/ubiquity/devpool-directory-private

**Comment by jordan-ae** [comment]
@pavlovcik To ensure this is working correctly I have to Auth as a core member. Please how can I archive that as I presently don't know how to do so.

**Comment by rndquu** [comment]
> This should ONLY populate with private repository issues.

https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json already contains only private repositories, I don't understand what additional checks should be implemented

> I just disabled it entirely in that repo as a quick fix by disabling the logic if its not the public devpool-directory repo https://github.com/ubiquity/devpool-directory-private/blob/development/helpers/github.ts#L63

I think this quick fix is already removed (I remember there was some check for organization name) but I couldn't find the exact commit

**Comment by jordan-ae** [comment]
@rndquu then there's no need for this issue to exist then?

**Comment by rndquu** [comment]
This issue may be closed as "not planned" because:
1. https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json already contains only private repositories (except for https://github.com/ubiquity/card-issuance which is public now but used to be private, not sure whether it should be public or private)
2. "referencing back to private repository issues" works as expected (check https://github.com/ubiquity/card-issuance/issues/34 which has a reference to `devpool-directory-private`)
<img width="1020" alt="Screenshot 2024-10-08 at 18 37 54" src="https://github.com/user-attachments/assets/3c782cf5-6fe9-4f48-b642-93a25ea359fb">

Overall it makes sense to setup [code sync](https://github.com/ubiquity/devpool-directory-bounties/issues/25) between `devpool-directory` and `devpool-directory-private` to make both code bases consistent.
