### ISSUE TITLE
Bug: Unlabeled Issues Fetched"

### ISSUE THREAD

**Issue by jordan-ae** [devpool-directory/devpool-directory-tasks#30]
@0x4007 I think this issue stemming from changes made on the backend, but the wrong issues are being populated on the frontend.

![Screenshot from 2024-08-15 14-15-50](https://github.com/user-attachments/assets/6692a455-6c59-48a1-9996-37b959b5b221)

**Comment by 0x4007** [comment]
![image](https://github.com/user-attachments/assets/a289b35b-5191-4d7a-a9af-60bed3b3c780)


Yeah this is all messed up now. The new changes need to be fixed.

**Comment by 0x4007** [comment]
![image](https://github.com/user-attachments/assets/ecf076cb-0558-41af-9634-432561c21b22)

Pretty sure it's because xno-miner ran their bot and it didn't populate the labels. 

We need to ignore opened issues from anybody but our bot. 

Ideally we should not allow unauthorized issues to be opened at all, but in case they are, we should also handle this on our front end.

**Comment by jordan-ae** [comment]
If we check  `if (projectIssue.user?.login !== "ubiquibot") return;` when creating new issues it should avoid such. We could also have a similar check to load issues on the frontend only if the owner is `ubiquibot`. Think this should work.

**Comment by 0x4007** [comment]
> If we check `if (projectIssue.user?.login !== "ubiquibot") return;` when creating new issues it should avoid such. We could also have a similar check to load issues on the frontend only if the owner is `ubiquibot`. Think this should work.

1. We should **delete** (not close) the issues created by unauthorized entities. This removes pollution of the `devpool-directory` issues
2. Dynamically check if our organizations, based on organization ID, own the bot attempting to open the issue. Then consider them authorized. That way when we create new bots, as we do, we don't have to keep updating this code. 

`76412717`@ubiquity 
`133917611`@ubiquibot
`165700353`@ubiquityos

**Comment by jordan-ae** [comment]
Sound Great, the only little blocker is that its not possible to  [ delete an issue ](https://github.com/octokit/octokit.js/discussions/2343) directly with the octokit API. The only option is to close the issue[](url)

**Comment by Keyrxng** [comment]
Seems like you need admin permissions and it has to be enabled at the org level for this to be possible via the UI too

https://docs.github.com/en/organizations/managing-organization-settings/allowing-people-to-delete-issues-in-your-organization

It's likely possible via GitHub CLI script [example here](https://gist.github.com/Tyrrrz/7bf335f3a6b41ba0deabb42a9bef7e3c) which if it is still possible we could write a script and run it in the workflow with an admin auth token as a repo secret

I guess they make it hard because it could be dangerous to programmatically delete lots of issues so if this is the route we need to take it should be safeguarded to ensure we don't pop legit issues.

**Comment by rndquu** [comment]
There's no bug with "Unlabeled issues" since they were simply created by the `xno-miner`'s app `testbot6` used for testing purposes. This issue could be closed in favor of https://github.com/ubiquity/devpool-directory-bounties/issues/31.

**Comment by rndquu** [comment]
@jordan-ae As a part of this issue you're going to delete github issues created not by the bot (as described [here](https://github.com/ubiquity/devpool-directory-bounties/issues/31#issue-2473357994)), right? If so then I'll close https://github.com/ubiquity/devpool-directory-bounties/issues/31 as "not planned".
