### ISSUE TITLE
@ubiquity-os Organization no Longer Syncing

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#39]
I renamed the organization from "Ubiquity-OS" to "ubiquity-os" in the URL. I also renamed the organization "display name" from Ubiquity-OS" to "UbiquityOS"

I noticed now that it no longer 1. displays on https://devpool.directory or 2. syncs to the backend. 

Please research and implement a sustainable fix for if this ever happens again. 

- Example task https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/7

![work ubq fi_](https://github.com/user-attachments/assets/5871f187-52d4-484d-9797-1acef9a5981c)

**Comment by 0x4007** [comment]
@Keyrxng perhaps you can look into this

**Comment by Keyrxng** [comment]
There is a collection of issues within the devpool that currently have an `id:` label which should be the node_id of the task which it relates to however the extracted node_id doesn't correlate to an issue at all. 

Some repos [do not exist](https://github.com/ubiquity/github-agents/issues/1) anymore, others have been renamed such as `bounty-bot` which is now `devpool-directory-bounties`. I scrubbed issue timelines for erroneous node_id label changes and a host of others debug ideas but came up short.

I was under the impression that a `node_id` was immutable once created but this proves that theory wrong I think.

<details><summary>Json log</summary>

```json
[
    {
        "title": "Pull Precheck",
        "url": "https://github.com/ubiquity/devpool-directory/issues/1504",
        "partnerTaskId": "I_kwDOMoorW86WmQEU",
        "realTaskId": "I_kwDOLf0nHM6XQr8T",
        "devpoolBody": "https://github.com/ubiquibot/plugins-wishlist/issues/45"
    },
    {
        "title": "Save permits to DB",
        "url": "https://github.com/ubiquity/devpool-directory/issues/1114",
        "partnerTaskId": "I_kwDOK87YcM6BZcHg",
        "realTaskId": "I_kwDOLUK0B86GWaEU",
        "devpoolBody": "https://github.com/ubiquibot/conversation-rewards/issues/13"
    },
    {
        "title": "Implement Dynamic RPC pick handler",
        "url": "https://github.com/ubiquity/devpool-directory/issues/1088",
        "partnerTaskId": "I_kwDOI-EJSM6AcrGo",
        "realTaskId": "I_kwDOLaI9PM6CQxNq",
        "devpoolBody": "https://github.com/ubiquity/rpc-handler/issues/3"
    },
    {
        "title": "Audit: Sign in with GitHub",
        "url": "https://github.com/ubiquity/devpool-directory/issues/1078",
        "partnerTaskId": "I_kwDOI-EJSM5_8_d9",
        "realTaskId": "I_kwDOLZ8eH86BDnCB",
        "devpoolBody": "https://github.com/ubiquity/audit.ubq.fi/issues/3"
    },
    {
        "title": "Generate Default Organization Configuration App",
        "url": "https://github.com/ubiquity/devpool-directory/issues/1060",
        "partnerTaskId": "I_kwDOI-EJSM5_VX4t",
        "realTaskId": "I_kwDOLaCxqM6BBQ8W",
        "devpoolBody": "https://github.com/ubiquity/onboard.ubq.fi/issues/3"
    },
    {
        "title": "Onboarding: Support Multi Token Rewards",
        "url": "https://github.com/ubiquity/devpool-directory/issues/925",
        "partnerTaskId": "I_kwDOI-EJSM5xEC1u",
        "realTaskId": "I_kwDOLaCxqM6BDm7H",
        "devpoolBody": "https://github.com/ubiquity/onboard.ubq.fi/issues/6"
    },
    {
        "title": "Task Assignee Reward Crash",
        "url": "https://github.com/ubiquity/devpool-directory/issues/874",
        "partnerTaskId": "I_kwDOF4fVBs5vh2zg",
        "realTaskId": "I_kwDOH92Z-c5vh8PP",
        "devpoolBody": "https://github.com/ubiquity/ubiquibot/issues/687"
    },
    {
        "title": "`audit` dApp: Show issues with unclaimed permits",
        "url": "https://github.com/ubiquity/devpool-directory/issues/788",
        "partnerTaskId": "I_kwDOI-EJSM5slMnz",
        "realTaskId": "I_kwDOLZ8eH86BDnP2",
        "devpoolBody": "https://github.com/ubiquity/audit.ubq.fi/issues/5"
    },
    {
        "title": "AI Trained Agents as Assistants",
        "url": "https://github.com/ubiquity/devpool-directory/issues/739",
        "partnerTaskId": "I_kwDOJ4cf685qz32W",
        "realTaskId": "Not found",
        "devpoolBody": "https://github.com/ubiquity/github-agents/issues/1"
    },
    {
        "title": "Proposal: Customize Automated QA Project Author ",
        "url": "https://github.com/ubiquity/devpool-directory/issues/723",
        "partnerTaskId": "I_kwDOJ0fZY85qoOwE",
        "realTaskId": "Not found",
        "devpoolBody": "https://github.com/ubiquibot/quality-assurance-improvements/issues/3"
    },
    {
        "title": "Automate QA issue creation ",
        "url": "https://github.com/ubiquity/devpool-directory/issues/711",
        "partnerTaskId": "I_kwDOJ0fZY85p2w2X",
        "realTaskId": "Not found",
        "devpoolBody": "https://github.com/ubiquibot/quality-assurance-improvements/issues/1"
    },
    {
        "title": "Create a Staging version of `https://pay.ubq.fi/secret`",
        "url": "https://github.com/ubiquity/devpool-directory/issues/710",
        "partnerTaskId": "I_kwDOJ0fZY85qGGNa",
        "realTaskId": "Not found",
        "devpoolBody": "https://github.com/ubiquibot/quality-assurance-improvements/issues/2"
    },
    {
        "title": "Close Pull Request When `Unassigned`",
        "url": "https://github.com/ubiquity/devpool-directory/issues/659",
        "partnerTaskId": "I_kwDOF4fVBs5nuzha",
        "realTaskId": "I_kwDOH92Z-c5oDO1e",
        "devpoolBody": "https://github.com/ubiquity/ubiquibot/issues/379"
    },
    {
        "title": "Implement stale issues report",
        "url": "https://github.com/ubiquity/devpool-directory/issues/551",
        "partnerTaskId": "I_kwDOH92Z-c5ddbM-",
        "realTaskId": "Not found",
        "devpoolBody": "https://github.com/ubiquity/bounty-bot/issues/99"
    },
    {
        "title": "\"Initial commit\" commit message does not pass conventional commits",
        "url": "https://github.com/ubiquity/devpool-directory/issues/510",
        "partnerTaskId": "I_kwDOJGfp8c5k7xfK",
        "realTaskId": "I_kwDOJTzPsc5qGj55",
        "devpoolBody": "https://github.com/ubiquity/action-conventional-commits/issues/3"
    },
    {
        "title": "Audits: Owed Payments (Unpaid But Permitted)",
        "url": "https://github.com/ubiquity/devpool-directory/issues/505",
        "partnerTaskId": "I_kwDOI-EJSM5jLy30",
        "realTaskId": "I_kwDOLZ8eH86BDnIi",
        "devpoolBody": "https://github.com/ubiquity/audit.ubq.fi/issues/4"
    },
    {
        "title": "Match ethereum tx with github issue onchain",
        "url": "https://github.com/ubiquity/devpool-directory/issues/504",
        "partnerTaskId": "I_kwDOI-EJSM5jlVeL",
        "realTaskId": "I_kwDOLZ8eH86JrnAA",
        "devpoolBody": "https://github.com/ubiquity/audit.ubq.fi/issues/12"
    }
]
```

</details>

---

#27 was making it difficult to debug alone so I had to resolve that which includes a refactoring of statistics too.

I noticed that issues that had been transferred have kept their old partner label rather than the new repo that would come with a new `node_id` by the looks of things.

I think the issues have been caused by a combination of both the `Unavailable` label and this `node_id` discrepancy, as well as some slightly off boolean logic causing the body to be modified even when `isFork: false` on select tasks.

I hope that this also addresses #39 but I can't be sure of that until merged and tested in prod because of the fork conditions applied but locally it looks promising as I'm seeing issues being created which are currently being missed by the `sync-issues` workflow and out-of-sync `node_id` labels being updated etc.

My debugging has been against production locally. I started writing a spec a couple hours in and felt I had nothing of value to provide so I've waited until I knew more but here's a [gist](https://gist.github.com/Keyrxng/141b833dc62f086214dc28b15542dae5) I was going to share early on.

---

As I've covered multiple tasks, rather than open one big PR I'll open few targeting different fixes, bit late now and I'm awfully tired. Tests will require factoring too which I haven't ran since the PR I merged this morning which seems like a a day or two ago 🤣

I intended for this comment to be a spec at first, but I don't want to be appear to be task dipping, but should I open multiple PRs to this one issue or open small tasks for the specific fixes and link them back to this?


##### P.S: I've intentionally focused on just this all day today as I want to get it squared away without any distraction or losing myself in conversation. I don't feel like I've shipped much recently and comments can sometimes take me hours to write 😂

**Comment by 0x4007** [comment]
Yeah break them off into separate tasks and then associate a single pull to each. 

I suppose it would have been proper to make a checklist here and turn  it into a parent task

**Comment by 0x4007** [comment]
Looks like this fixed itself. No idea what happened.

<img width="643" alt="image" src="https://github.com/user-attachments/assets/72a6c9f8-2cf7-48f7-bfe1-c8f7f350eff7">

**Comment by Keyrxng** [comment]
the recent merge is why it seems to have resolved, I at first thought the backend had broken but it looks like that was the intention, it was mostly the old labels like `Permitted` that threw me off.

https://github.com/ubiquity/devpool-directory/issues

![image](https://github.com/user-attachments/assets/0993ec8a-69d9-4463-a337-874907df3c97)
