### ISSUE TITLE
/assign

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#6]
What is the best way to handle this situation? It's sensible to request the bounty directly in the directory. Written instructions in the README may be sufficient, but I wish the information could be presented exactly when needed to reduce friction for new bounty hunters.

Also we need to make sure that after we import the labels, that the bot doesn't try and price the bounties in the directory!

---

              /assign

_Originally posted by @eugenioclrc in https://github.com/ubiquity/devpool-directory/issues/603#issuecomment-1551474188_

**Comment by 0x4007** [comment]
@rndquu request for comment

**Comment by rndquu** [comment]
We can add a "blacklist" feature that disables bot functions (i.e. commands) and stops listening for events for certain repos, that would be useful both for our case and future partners with scam related projects. 

We can also add a new bot's param like `msg-blacklisted` (which should be a bot's response for any command in a blacklisted project) and set it to `You can not assign yourself to the issues inside of this repository. Instead, you must navigate to the linked issue, and write /assign there in order to take a bounty.` for the https://github.com/ubiquity/devpool-directory repo

**Comment by 0x4007** [comment]
> "blacklist" feature

Seems useful. However, we will need to hide the documentation around this in order to outsmart the projects we don't want to be associated with. Couldn't we, as the bot (GitHub App) operators, ban from the GitHub App level instead? I would think that GitHub would support this type of behavior already. If not, then disabling features from the runtime logic could be a superior idea.

**Comment by rndquu** [comment]
We could try to [suspend](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#suspend-an-app-installation) an app for the https://github.com/ubiquity/devpool-directory

I don't know if the bot would be able to get an installation token in this case (for posting bounties under the bot's name). I'll check it

**Comment by 0x4007** [comment]
@rndquu would you be able to convert this into an actionable bounty and we can set a price?

**Comment by rndquu** [comment]
> @rndquu would you be able to convert this into an actionable bounty and we can set a price?

https://github.com/ubiquity/ubiquibot/issues/396

P.S. we can't use the [suspend app API](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#suspend-an-app-installation) for certain repos (i.e. we can't simply suspend the bot for https://github.com/ubiquity/devpool-directory) because in this case the bot loses access to github API which it needs for creating/updating bounties

**Comment by rndquu** [comment]
@pavlovcik we can close this one because the [blacklist feature](https://github.com/ubiquity/ubiquibot/issues/396) will eliminate such [cases](https://github.com/ubiquity/devpool-directory/issues/603#issuecomment-1551474188) (when bounty hunter tries to self assign issues in https://github.com/ubiquity/devpool-directory instead of https://github.com/ubiquity/devpool-directory-bounties)
